//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBasics.Cms.Model
{
	using System;
	using MySoft.Data;


	/// <summary>
	/// 表名：wbcms_AnyFile 主键列：ID
	/// </summary>
	[SerializableAttribute()]
	public partial class AnyFile : Entity
	{

		protected Guid _ID;

		protected DateTime _AddTime;

		protected DateTime _UpdateTime;

		protected Boolean _IsDeleted;

		protected Byte _DeleteReason;

		protected Guid? _ChannelID;

		protected String _Title;

		protected String _Summary;

		protected String _Body;

		protected String _Tags;

		protected String _From;

		protected String _Author;

		protected String _Instructor;

		protected Guid? _UserID;

		protected Guid? _AdminID;

		protected DateTime _OccurTime;

		protected Byte _AuditStatus;

		protected String _FileName;

		protected String _FileExtension;

		protected Single _FileSize;

		protected String _FileUrl;

		protected String _ThumbnailUrl;

		protected Byte _FileType;

		public Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				this.OnPropertyValueChange(_.ID, _ID, value);
				this._ID = value;
			}
		}

		public DateTime AddTime
		{
			get
			{
				return this._AddTime;
			}
			set
			{
				this.OnPropertyValueChange(_.AddTime, _AddTime, value);
				this._AddTime = value;
			}
		}

		public DateTime UpdateTime
		{
			get
			{
				return this._UpdateTime;
			}
			set
			{
				this.OnPropertyValueChange(_.UpdateTime, _UpdateTime, value);
				this._UpdateTime = value;
			}
		}

		public Boolean IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				this.OnPropertyValueChange(_.IsDeleted, _IsDeleted, value);
				this._IsDeleted = value;
			}
		}

		public Byte DeleteReason
		{
			get
			{
				return this._DeleteReason;
			}
			set
			{
				this.OnPropertyValueChange(_.DeleteReason, _DeleteReason, value);
				this._DeleteReason = value;
			}
		}

		public Guid? ChannelID
		{
			get
			{
				return this._ChannelID;
			}
			set
			{
				this.OnPropertyValueChange(_.ChannelID, _ChannelID, value);
				this._ChannelID = value;
			}
		}

		public String Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				this.OnPropertyValueChange(_.Title, _Title, value);
				this._Title = value;
			}
		}

		public String Summary
		{
			get
			{
				return this._Summary;
			}
			set
			{
				this.OnPropertyValueChange(_.Summary, _Summary, value);
				this._Summary = value;
			}
		}

		public String Body
		{
			get
			{
				return this._Body;
			}
			set
			{
				this.OnPropertyValueChange(_.Body, _Body, value);
				this._Body = value;
			}
		}

		public String Tags
		{
			get
			{
				return this._Tags;
			}
			set
			{
				this.OnPropertyValueChange(_.Tags, _Tags, value);
				this._Tags = value;
			}
		}

		public String From
		{
			get
			{
				return this._From;
			}
			set
			{
				this.OnPropertyValueChange(_.From, _From, value);
				this._From = value;
			}
		}

		public String Author
		{
			get
			{
				return this._Author;
			}
			set
			{
				this.OnPropertyValueChange(_.Author, _Author, value);
				this._Author = value;
			}
		}

		public String Instructor
		{
			get
			{
				return this._Instructor;
			}
			set
			{
				this.OnPropertyValueChange(_.Instructor, _Instructor, value);
				this._Instructor = value;
			}
		}

		public Guid? UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				this.OnPropertyValueChange(_.UserID, _UserID, value);
				this._UserID = value;
			}
		}

		public Guid? AdminID
		{
			get
			{
				return this._AdminID;
			}
			set
			{
				this.OnPropertyValueChange(_.AdminID, _AdminID, value);
				this._AdminID = value;
			}
		}

		public DateTime OccurTime
		{
			get
			{
				return this._OccurTime;
			}
			set
			{
				this.OnPropertyValueChange(_.OccurTime, _OccurTime, value);
				this._OccurTime = value;
			}
		}

		public Byte AuditStatus
		{
			get
			{
				return this._AuditStatus;
			}
			set
			{
				this.OnPropertyValueChange(_.AuditStatus, _AuditStatus, value);
				this._AuditStatus = value;
			}
		}

		public String FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				this.OnPropertyValueChange(_.FileName, _FileName, value);
				this._FileName = value;
			}
		}

		public String FileExtension
		{
			get
			{
				return this._FileExtension;
			}
			set
			{
				this.OnPropertyValueChange(_.FileExtension, _FileExtension, value);
				this._FileExtension = value;
			}
		}

		public Single FileSize
		{
			get
			{
				return this._FileSize;
			}
			set
			{
				this.OnPropertyValueChange(_.FileSize, _FileSize, value);
				this._FileSize = value;
			}
		}

		public String FileUrl
		{
			get
			{
				return this._FileUrl;
			}
			set
			{
				this.OnPropertyValueChange(_.FileUrl, _FileUrl, value);
				this._FileUrl = value;
			}
		}

		public String ThumbnailUrl
		{
			get
			{
				return this._ThumbnailUrl;
			}
			set
			{
				this.OnPropertyValueChange(_.ThumbnailUrl, _ThumbnailUrl, value);
				this._ThumbnailUrl = value;
			}
		}

		public Byte FileType
		{
			get
			{
				return this._FileType;
			}
			set
			{
				this.OnPropertyValueChange(_.FileType, _FileType, value);
				this._FileType = value;
			}
		}

		/// <summary>
		/// 获取实体对应的表名
		/// </summary>
		protected override Table GetTable()
		{
			return new Table<AnyFile>("wbcms_AnyFile");
		}

		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		protected override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
                        _.ID};
		}

		/// <summary>
		/// 获取列信息
		/// </summary>
		protected override Field[] GetFields()
		{
			return new Field[] {
                        _.ID,
                        _.AddTime,
                        _.UpdateTime,
                        _.IsDeleted,
                        _.DeleteReason,
                        _.ChannelID,
                        _.Title,
                        _.Summary,
                        _.Body,
                        _.Tags,
                        _.From,
                        _.Author,
                        _.Instructor,
                        _.UserID,
                        _.AdminID,
                        _.OccurTime,
                        _.AuditStatus,
                        _.FileName,
                        _.FileExtension,
                        _.FileSize,
                        _.FileUrl,
                        _.ThumbnailUrl,
                        _.FileType};
		}

		/// <summary>
		/// 获取列数据
		/// </summary>
		protected override object[] GetValues()
		{
			return new object[] {
                        this._ID,
                        this._AddTime,
                        this._UpdateTime,
                        this._IsDeleted,
                        this._DeleteReason,
                        this._ChannelID,
                        this._Title,
                        this._Summary,
                        this._Body,
                        this._Tags,
                        this._From,
                        this._Author,
                        this._Instructor,
                        this._UserID,
                        this._AdminID,
                        this._OccurTime,
                        this._AuditStatus,
                        this._FileName,
                        this._FileExtension,
                        this._FileSize,
                        this._FileUrl,
                        this._ThumbnailUrl,
                        this._FileType};
		}

		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		protected override void SetValues(IRowReader reader)
		{
			if ((false == reader.IsDBNull(_.ID)))
			{
				this._ID = reader.GetGuid(_.ID);
			}
			if ((false == reader.IsDBNull(_.AddTime)))
			{
				this._AddTime = reader.GetDateTime(_.AddTime);
			}
			if ((false == reader.IsDBNull(_.UpdateTime)))
			{
				this._UpdateTime = reader.GetDateTime(_.UpdateTime);
			}
			if ((false == reader.IsDBNull(_.IsDeleted)))
			{
				this._IsDeleted = reader.GetBoolean(_.IsDeleted);
			}
			if ((false == reader.IsDBNull(_.DeleteReason)))
			{
				this._DeleteReason = reader.GetByte(_.DeleteReason);
			}
			if ((false == reader.IsDBNull(_.ChannelID)))
			{
				this._ChannelID = reader.GetGuid(_.ChannelID);
			}
			if ((false == reader.IsDBNull(_.Title)))
			{
				this._Title = reader.GetString(_.Title);
			}
			if ((false == reader.IsDBNull(_.Summary)))
			{
				this._Summary = reader.GetString(_.Summary);
			}
			if ((false == reader.IsDBNull(_.Body)))
			{
				this._Body = reader.GetString(_.Body);
			}
			if ((false == reader.IsDBNull(_.Tags)))
			{
				this._Tags = reader.GetString(_.Tags);
			}
			if ((false == reader.IsDBNull(_.From)))
			{
				this._From = reader.GetString(_.From);
			}
			if ((false == reader.IsDBNull(_.Author)))
			{
				this._Author = reader.GetString(_.Author);
			}
			if ((false == reader.IsDBNull(_.Instructor)))
			{
				this._Instructor = reader.GetString(_.Instructor);
			}
			if ((false == reader.IsDBNull(_.UserID)))
			{
				this._UserID = reader.GetGuid(_.UserID);
			}
			if ((false == reader.IsDBNull(_.AdminID)))
			{
				this._AdminID = reader.GetGuid(_.AdminID);
			}
			if ((false == reader.IsDBNull(_.OccurTime)))
			{
				this._OccurTime = reader.GetDateTime(_.OccurTime);
			}
			if ((false == reader.IsDBNull(_.AuditStatus)))
			{
				this._AuditStatus = reader.GetByte(_.AuditStatus);
			}
			if ((false == reader.IsDBNull(_.FileName)))
			{
				this._FileName = reader.GetString(_.FileName);
			}
			if ((false == reader.IsDBNull(_.FileExtension)))
			{
				this._FileExtension = reader.GetString(_.FileExtension);
			}
			if ((false == reader.IsDBNull(_.FileSize)))
			{
				this._FileSize = reader.GetFloat(_.FileSize);
			}
			if ((false == reader.IsDBNull(_.FileUrl)))
			{
				this._FileUrl = reader.GetString(_.FileUrl);
			}
			if ((false == reader.IsDBNull(_.ThumbnailUrl)))
			{
				this._ThumbnailUrl = reader.GetString(_.ThumbnailUrl);
			}
			if ((false == reader.IsDBNull(_.FileType)))
			{
				this._FileType = reader.GetByte(_.FileType);
			}
		}

		public override int GetHashCode()
		{
			return base.GetHashCode();
		}

		public override bool Equals(object obj)
		{
			if ((obj == null))
			{
				return false;
			}
			if ((false == typeof(AnyFile).IsAssignableFrom(obj.GetType())))
			{
				return false;
			}
			if ((((object)(this)) == ((object)(obj))))
			{
				return true;
			}
			return false;
		}

		public class _
		{

			/// <summary>
			/// 表示选择所有列，与*等同
			/// </summary>
			public static AllField All = new AllField<AnyFile>();

			/// <summary>
			/// 字段名：ID - 数据类型：Guid
			/// </summary>
			public static Field ID = new Field<AnyFile>("ID");

			/// <summary>
			/// 字段名：AddTime - 数据类型：DateTime
			/// </summary>
			public static Field AddTime = new Field<AnyFile>("AddTime");

			/// <summary>
			/// 字段名：UpdateTime - 数据类型：DateTime
			/// </summary>
			public static Field UpdateTime = new Field<AnyFile>("UpdateTime");

			/// <summary>
			/// 字段名：IsDeleted - 数据类型：Boolean
			/// </summary>
			public static Field IsDeleted = new Field<AnyFile>("IsDeleted");

			/// <summary>
			/// 字段名：DeleteReason - 数据类型：Byte
			/// </summary>
			public static Field DeleteReason = new Field<AnyFile>("DeleteReason");

			/// <summary>
			/// 字段名：ChannelID - 数据类型：Nullable`1
			/// </summary>
			public static Field ChannelID = new Field<AnyFile>("ChannelID");

			/// <summary>
			/// 字段名：Title - 数据类型：String
			/// </summary>
			public static Field Title = new Field<AnyFile>("Title");

			/// <summary>
			/// 字段名：Summary - 数据类型：String
			/// </summary>
			public static Field Summary = new Field<AnyFile>("Summary");

			/// <summary>
			/// 字段名：Body - 数据类型：String
			/// </summary>
			public static Field Body = new Field<AnyFile>("Body");

			/// <summary>
			/// 字段名：Tags - 数据类型：String
			/// </summary>
			public static Field Tags = new Field<AnyFile>("Tags");

			/// <summary>
			/// 字段名：From - 数据类型：String
			/// </summary>
			public static Field From = new Field<AnyFile>("From");

			/// <summary>
			/// 字段名：Author - 数据类型：String
			/// </summary>
			public static Field Author = new Field<AnyFile>("Author");

			/// <summary>
			/// 字段名：Instructor - 数据类型：String
			/// </summary>
			public static Field Instructor = new Field<AnyFile>("Instructor");

			/// <summary>
			/// 字段名：UserID - 数据类型：Nullable`1
			/// </summary>
			public static Field UserID = new Field<AnyFile>("UserID");

			/// <summary>
			/// 字段名：AdminID - 数据类型：Nullable`1
			/// </summary>
			public static Field AdminID = new Field<AnyFile>("AdminID");

			/// <summary>
			/// 字段名：OccurTime - 数据类型：DateTime
			/// </summary>
			public static Field OccurTime = new Field<AnyFile>("OccurTime");

			/// <summary>
			/// 字段名：AuditStatus - 数据类型：Byte
			/// </summary>
			public static Field AuditStatus = new Field<AnyFile>("AuditStatus");

			/// <summary>
			/// 字段名：FileName - 数据类型：String
			/// </summary>
			public static Field FileName = new Field<AnyFile>("FileName");

			/// <summary>
			/// 字段名：FileExtension - 数据类型：String
			/// </summary>
			public static Field FileExtension = new Field<AnyFile>("FileExtension");

			/// <summary>
			/// 字段名：FileSize - 数据类型：Single
			/// </summary>
			public static Field FileSize = new Field<AnyFile>("FileSize");

			/// <summary>
			/// 字段名：FileUrl - 数据类型：String
			/// </summary>
			public static Field FileUrl = new Field<AnyFile>("FileUrl");

			/// <summary>
			/// 字段名：ThumbnailUrl - 数据类型：String
			/// </summary>
			public static Field ThumbnailUrl = new Field<AnyFile>("ThumbnailUrl");

			/// <summary>
			/// 字段名：FileType - 数据类型：Byte
			/// </summary>
			public static Field FileType = new Field<AnyFile>("FileType");
		}
	}
}
