//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouTong.Model
{
	using System;
	using MySoft.Data;


	/// <summary>
	/// 表名：ut_Area 主键列：ID
	/// </summary>
	[SerializableAttribute()]
	public partial class Area : Entity
	{

		protected Int32 _ID;

		protected DateTime _AddTime;

		protected DateTime _UpdateTime;

		protected Boolean _IsDeleted;

		protected String _Name;

		protected Boolean? _Hot;

		protected String _Description;

		protected Int32? _ParentID;

		public Int32 ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				this.OnPropertyValueChange(_.ID, _ID, value);
				this._ID = value;
			}
		}

		public DateTime AddTime
		{
			get
			{
				return this._AddTime;
			}
			set
			{
				this.OnPropertyValueChange(_.AddTime, _AddTime, value);
				this._AddTime = value;
			}
		}

		public DateTime UpdateTime
		{
			get
			{
				return this._UpdateTime;
			}
			set
			{
				this.OnPropertyValueChange(_.UpdateTime, _UpdateTime, value);
				this._UpdateTime = value;
			}
		}

		public Boolean IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				this.OnPropertyValueChange(_.IsDeleted, _IsDeleted, value);
				this._IsDeleted = value;
			}
		}

		public String Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				this.OnPropertyValueChange(_.Name, _Name, value);
				this._Name = value;
			}
		}

		public Boolean? Hot
		{
			get
			{
				return this._Hot;
			}
			set
			{
				this.OnPropertyValueChange(_.Hot, _Hot, value);
				this._Hot = value;
			}
		}

		public String Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				this.OnPropertyValueChange(_.Description, _Description, value);
				this._Description = value;
			}
		}

		public Int32? ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				this.OnPropertyValueChange(_.ParentID, _ParentID, value);
				this._ParentID = value;
			}
		}

		/// <summary>
		/// 获取实体对应的表名
		/// </summary>
		protected override Table GetTable()
		{
			return new Table<Area>("ut_Area");
		}

		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		protected override Field GetIdentityField()
		{
			return _.ID;
		}

		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		protected override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
                        _.ID};
		}

		/// <summary>
		/// 获取列信息
		/// </summary>
		protected override Field[] GetFields()
		{
			return new Field[] {
                        _.ID,
                        _.AddTime,
                        _.UpdateTime,
                        _.IsDeleted,
                        _.Name,
                        _.Hot,
                        _.Description,
                        _.ParentID};
		}

		/// <summary>
		/// 获取列数据
		/// </summary>
		protected override object[] GetValues()
		{
			return new object[] {
                        this._ID,
                        this._AddTime,
                        this._UpdateTime,
                        this._IsDeleted,
                        this._Name,
                        this._Hot,
                        this._Description,
                        this._ParentID};
		}

		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		protected override void SetValues(IRowReader reader)
		{
			if ((false == reader.IsDBNull(_.ID)))
			{
				this._ID = reader.GetInt32(_.ID);
			}
			if ((false == reader.IsDBNull(_.AddTime)))
			{
				this._AddTime = reader.GetDateTime(_.AddTime);
			}
			if ((false == reader.IsDBNull(_.UpdateTime)))
			{
				this._UpdateTime = reader.GetDateTime(_.UpdateTime);
			}
			if ((false == reader.IsDBNull(_.IsDeleted)))
			{
				this._IsDeleted = reader.GetBoolean(_.IsDeleted);
			}
			if ((false == reader.IsDBNull(_.Name)))
			{
				this._Name = reader.GetString(_.Name);
			}
			if ((false == reader.IsDBNull(_.Hot)))
			{
				this._Hot = reader.GetBoolean(_.Hot);
			}
			if ((false == reader.IsDBNull(_.Description)))
			{
				this._Description = reader.GetString(_.Description);
			}
			if ((false == reader.IsDBNull(_.ParentID)))
			{
				this._ParentID = reader.GetInt32(_.ParentID);
			}
		}

		public override int GetHashCode()
		{
			return base.GetHashCode();
		}

		public override bool Equals(object obj)
		{
			if ((obj == null))
			{
				return false;
			}
			if ((false == typeof(Area).IsAssignableFrom(obj.GetType())))
			{
				return false;
			}
			if ((((object)(this)) == ((object)(obj))))
			{
				return true;
			}
			return false;
		}

		public class _
		{

			/// <summary>
			/// 表示选择所有列，与*等同
			/// </summary>
			public static AllField All = new AllField<Area>();

			/// <summary>
			/// 字段名：ID - 数据类型：Int32
			/// </summary>
			public static Field ID = new Field<Area>("ID");

			/// <summary>
			/// 字段名：AddTime - 数据类型：DateTime
			/// </summary>
			public static Field AddTime = new Field<Area>("AddTime");

			/// <summary>
			/// 字段名：UpdateTime - 数据类型：DateTime
			/// </summary>
			public static Field UpdateTime = new Field<Area>("UpdateTime");

			/// <summary>
			/// 字段名：IsDeleted - 数据类型：Boolean
			/// </summary>
			public static Field IsDeleted = new Field<Area>("IsDeleted");

			/// <summary>
			/// 字段名：Name - 数据类型：String
			/// </summary>
			public static Field Name = new Field<Area>("Name");

			/// <summary>
			/// 字段名：Hot - 数据类型：Nullable`1
			/// </summary>
			public static Field Hot = new Field<Area>("Hot");

			/// <summary>
			/// 字段名：Description - 数据类型：String
			/// </summary>
			public static Field Description = new Field<Area>("Description");

			/// <summary>
			/// 字段名：ParentID - 数据类型：Nullable`1
			/// </summary>
			public static Field ParentID = new Field<Area>("ParentID");
		}
	}
}
