//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouTong.Model
{
	using System;
	using MySoft.Data;


	/// <summary>
	/// 表名：ut_Resume 主键列：ID
	/// </summary>
	[SerializableAttribute()]
	public partial class Resume : Entity
	{

		protected Guid _ID;

		protected DateTime _AddTime;

		protected DateTime _UpdateTime;

		protected Boolean _IsDeleted;

		protected Guid _ChildID;

		protected DateTime _StartDate;

		protected DateTime? _EndDate;

		protected String _Title;

		protected String _Body;

		public Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				this.OnPropertyValueChange(_.ID, _ID, value);
				this._ID = value;
			}
		}

		public DateTime AddTime
		{
			get
			{
				return this._AddTime;
			}
			set
			{
				this.OnPropertyValueChange(_.AddTime, _AddTime, value);
				this._AddTime = value;
			}
		}

		public DateTime UpdateTime
		{
			get
			{
				return this._UpdateTime;
			}
			set
			{
				this.OnPropertyValueChange(_.UpdateTime, _UpdateTime, value);
				this._UpdateTime = value;
			}
		}

		public Boolean IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				this.OnPropertyValueChange(_.IsDeleted, _IsDeleted, value);
				this._IsDeleted = value;
			}
		}

		public Guid ChildID
		{
			get
			{
				return this._ChildID;
			}
			set
			{
				this.OnPropertyValueChange(_.ChildID, _ChildID, value);
				this._ChildID = value;
			}
		}

		public DateTime StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				this.OnPropertyValueChange(_.StartDate, _StartDate, value);
				this._StartDate = value;
			}
		}

		public DateTime? EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				this.OnPropertyValueChange(_.EndDate, _EndDate, value);
				this._EndDate = value;
			}
		}

		public String Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				this.OnPropertyValueChange(_.Title, _Title, value);
				this._Title = value;
			}
		}

		public String Body
		{
			get
			{
				return this._Body;
			}
			set
			{
				this.OnPropertyValueChange(_.Body, _Body, value);
				this._Body = value;
			}
		}

		/// <summary>
		/// 获取实体对应的表名
		/// </summary>
		protected override Table GetTable()
		{
			return new Table<Resume>("ut_Resume");
		}

		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		protected override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
                        _.ID};
		}

		/// <summary>
		/// 获取列信息
		/// </summary>
		protected override Field[] GetFields()
		{
			return new Field[] {
                        _.ID,
                        _.AddTime,
                        _.UpdateTime,
                        _.IsDeleted,
                        _.ChildID,
                        _.StartDate,
                        _.EndDate,
                        _.Title,
                        _.Body};
		}

		/// <summary>
		/// 获取列数据
		/// </summary>
		protected override object[] GetValues()
		{
			return new object[] {
                        this._ID,
                        this._AddTime,
                        this._UpdateTime,
                        this._IsDeleted,
                        this._ChildID,
                        this._StartDate,
                        this._EndDate,
                        this._Title,
                        this._Body};
		}

		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		protected override void SetValues(IRowReader reader)
		{
			if ((false == reader.IsDBNull(_.ID)))
			{
				this._ID = reader.GetGuid(_.ID);
			}
			if ((false == reader.IsDBNull(_.AddTime)))
			{
				this._AddTime = reader.GetDateTime(_.AddTime);
			}
			if ((false == reader.IsDBNull(_.UpdateTime)))
			{
				this._UpdateTime = reader.GetDateTime(_.UpdateTime);
			}
			if ((false == reader.IsDBNull(_.IsDeleted)))
			{
				this._IsDeleted = reader.GetBoolean(_.IsDeleted);
			}
			if ((false == reader.IsDBNull(_.ChildID)))
			{
				this._ChildID = reader.GetGuid(_.ChildID);
			}
			if ((false == reader.IsDBNull(_.StartDate)))
			{
				this._StartDate = reader.GetDateTime(_.StartDate);
			}
			if ((false == reader.IsDBNull(_.EndDate)))
			{
				this._EndDate = reader.GetDateTime(_.EndDate);
			}
			if ((false == reader.IsDBNull(_.Title)))
			{
				this._Title = reader.GetString(_.Title);
			}
			if ((false == reader.IsDBNull(_.Body)))
			{
				this._Body = reader.GetString(_.Body);
			}
		}

		public override int GetHashCode()
		{
			return base.GetHashCode();
		}

		public override bool Equals(object obj)
		{
			if ((obj == null))
			{
				return false;
			}
			if ((false == typeof(Resume).IsAssignableFrom(obj.GetType())))
			{
				return false;
			}
			if ((((object)(this)) == ((object)(obj))))
			{
				return true;
			}
			return false;
		}

		public class _
		{

			/// <summary>
			/// 表示选择所有列，与*等同
			/// </summary>
			public static AllField All = new AllField<Resume>();

			/// <summary>
			/// 字段名：ID - 数据类型：Guid
			/// </summary>
			public static Field ID = new Field<Resume>("ID");

			/// <summary>
			/// 字段名：AddTime - 数据类型：DateTime
			/// </summary>
			public static Field AddTime = new Field<Resume>("AddTime");

			/// <summary>
			/// 字段名：UpdateTime - 数据类型：DateTime
			/// </summary>
			public static Field UpdateTime = new Field<Resume>("UpdateTime");

			/// <summary>
			/// 字段名：IsDeleted - 数据类型：Boolean
			/// </summary>
			public static Field IsDeleted = new Field<Resume>("IsDeleted");

			/// <summary>
			/// 字段名：ChildID - 数据类型：Guid
			/// </summary>
			public static Field ChildID = new Field<Resume>("ChildID");

			/// <summary>
			/// 字段名：StartDate - 数据类型：DateTime
			/// </summary>
			public static Field StartDate = new Field<Resume>("StartDate");

			/// <summary>
			/// 字段名：EndDate - 数据类型：Nullable`1
			/// </summary>
			public static Field EndDate = new Field<Resume>("EndDate");

			/// <summary>
			/// 字段名：Title - 数据类型：String
			/// </summary>
			public static Field Title = new Field<Resume>("Title");

			/// <summary>
			/// 字段名：Body - 数据类型：String
			/// </summary>
			public static Field Body = new Field<Resume>("Body");
		}
	}
}
