//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBasics.Cms.Model
{
	using System;
	using MySoft.Data;


	/// <summary>
	/// 表名：wbcms_Article 主键列：ID
	/// </summary>
	[SerializableAttribute()]
	public partial class Article : Entity
	{

		protected Guid _ID;

		protected DateTime _AddTime;

		protected DateTime _UpdateTime;

		protected Boolean _IsDeleted;

		protected Byte _DeleteReason;

		protected Guid? _ChannelID;

		protected String _Title;

		protected String _Summary;

		protected String _Body;

		protected String _Tags;

		protected String _From;

		protected String _Author;

		protected String _Instructor;

		protected Guid? _UserID;

		protected Guid? _AdminID;

		protected DateTime _OccurTime;

		protected Byte _AuditStatus;

		protected Byte _Recommend;

		protected Byte _RelationalModel;

		public Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				this.OnPropertyValueChange(_.ID, _ID, value);
				this._ID = value;
			}
		}

		public DateTime AddTime
		{
			get
			{
				return this._AddTime;
			}
			set
			{
				this.OnPropertyValueChange(_.AddTime, _AddTime, value);
				this._AddTime = value;
			}
		}

		public DateTime UpdateTime
		{
			get
			{
				return this._UpdateTime;
			}
			set
			{
				this.OnPropertyValueChange(_.UpdateTime, _UpdateTime, value);
				this._UpdateTime = value;
			}
		}

		public Boolean IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				this.OnPropertyValueChange(_.IsDeleted, _IsDeleted, value);
				this._IsDeleted = value;
			}
		}

		public Byte DeleteReason
		{
			get
			{
				return this._DeleteReason;
			}
			set
			{
				this.OnPropertyValueChange(_.DeleteReason, _DeleteReason, value);
				this._DeleteReason = value;
			}
		}

		public Guid? ChannelID
		{
			get
			{
				return this._ChannelID;
			}
			set
			{
				this.OnPropertyValueChange(_.ChannelID, _ChannelID, value);
				this._ChannelID = value;
			}
		}

		public String Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				this.OnPropertyValueChange(_.Title, _Title, value);
				this._Title = value;
			}
		}

		public String Summary
		{
			get
			{
				return this._Summary;
			}
			set
			{
				this.OnPropertyValueChange(_.Summary, _Summary, value);
				this._Summary = value;
			}
		}

		public String Body
		{
			get
			{
				return this._Body;
			}
			set
			{
				this.OnPropertyValueChange(_.Body, _Body, value);
				this._Body = value;
			}
		}

		public String Tags
		{
			get
			{
				return this._Tags;
			}
			set
			{
				this.OnPropertyValueChange(_.Tags, _Tags, value);
				this._Tags = value;
			}
		}

		public String From
		{
			get
			{
				return this._From;
			}
			set
			{
				this.OnPropertyValueChange(_.From, _From, value);
				this._From = value;
			}
		}

		public String Author
		{
			get
			{
				return this._Author;
			}
			set
			{
				this.OnPropertyValueChange(_.Author, _Author, value);
				this._Author = value;
			}
		}

		public String Instructor
		{
			get
			{
				return this._Instructor;
			}
			set
			{
				this.OnPropertyValueChange(_.Instructor, _Instructor, value);
				this._Instructor = value;
			}
		}

		public Guid? UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				this.OnPropertyValueChange(_.UserID, _UserID, value);
				this._UserID = value;
			}
		}

		public Guid? AdminID
		{
			get
			{
				return this._AdminID;
			}
			set
			{
				this.OnPropertyValueChange(_.AdminID, _AdminID, value);
				this._AdminID = value;
			}
		}

		public DateTime OccurTime
		{
			get
			{
				return this._OccurTime;
			}
			set
			{
				this.OnPropertyValueChange(_.OccurTime, _OccurTime, value);
				this._OccurTime = value;
			}
		}

		public Byte AuditStatus
		{
			get
			{
				return this._AuditStatus;
			}
			set
			{
				this.OnPropertyValueChange(_.AuditStatus, _AuditStatus, value);
				this._AuditStatus = value;
			}
		}

		public Byte Recommend
		{
			get
			{
				return this._Recommend;
			}
			set
			{
				this.OnPropertyValueChange(_.Recommend, _Recommend, value);
				this._Recommend = value;
			}
		}

		public Byte RelationalModel
		{
			get
			{
				return this._RelationalModel;
			}
			set
			{
				this.OnPropertyValueChange(_.RelationalModel, _RelationalModel, value);
				this._RelationalModel = value;
			}
		}

		/// <summary>
		/// 获取实体对应的表名
		/// </summary>
		protected override Table GetTable()
		{
			return new Table<Article>("wbcms_Article");
		}

		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		protected override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
                        _.ID};
		}

		/// <summary>
		/// 获取列信息
		/// </summary>
		protected override Field[] GetFields()
		{
			return new Field[] {
                        _.ID,
                        _.AddTime,
                        _.UpdateTime,
                        _.IsDeleted,
                        _.DeleteReason,
                        _.ChannelID,
                        _.Title,
                        _.Summary,
                        _.Body,
                        _.Tags,
                        _.From,
                        _.Author,
                        _.Instructor,
                        _.UserID,
                        _.AdminID,
                        _.OccurTime,
                        _.AuditStatus,
                        _.Recommend,
                        _.RelationalModel};
		}

		/// <summary>
		/// 获取列数据
		/// </summary>
		protected override object[] GetValues()
		{
			return new object[] {
                        this._ID,
                        this._AddTime,
                        this._UpdateTime,
                        this._IsDeleted,
                        this._DeleteReason,
                        this._ChannelID,
                        this._Title,
                        this._Summary,
                        this._Body,
                        this._Tags,
                        this._From,
                        this._Author,
                        this._Instructor,
                        this._UserID,
                        this._AdminID,
                        this._OccurTime,
                        this._AuditStatus,
                        this._Recommend,
                        this._RelationalModel};
		}

		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		protected override void SetValues(IRowReader reader)
		{
			if ((false == reader.IsDBNull(_.ID)))
			{
				this._ID = reader.GetGuid(_.ID);
			}
			if ((false == reader.IsDBNull(_.AddTime)))
			{
				this._AddTime = reader.GetDateTime(_.AddTime);
			}
			if ((false == reader.IsDBNull(_.UpdateTime)))
			{
				this._UpdateTime = reader.GetDateTime(_.UpdateTime);
			}
			if ((false == reader.IsDBNull(_.IsDeleted)))
			{
				this._IsDeleted = reader.GetBoolean(_.IsDeleted);
			}
			if ((false == reader.IsDBNull(_.DeleteReason)))
			{
				this._DeleteReason = reader.GetByte(_.DeleteReason);
			}
			if ((false == reader.IsDBNull(_.ChannelID)))
			{
				this._ChannelID = reader.GetGuid(_.ChannelID);
			}
			if ((false == reader.IsDBNull(_.Title)))
			{
				this._Title = reader.GetString(_.Title);
			}
			if ((false == reader.IsDBNull(_.Summary)))
			{
				this._Summary = reader.GetString(_.Summary);
			}
			if ((false == reader.IsDBNull(_.Body)))
			{
				this._Body = reader.GetString(_.Body);
			}
			if ((false == reader.IsDBNull(_.Tags)))
			{
				this._Tags = reader.GetString(_.Tags);
			}
			if ((false == reader.IsDBNull(_.From)))
			{
				this._From = reader.GetString(_.From);
			}
			if ((false == reader.IsDBNull(_.Author)))
			{
				this._Author = reader.GetString(_.Author);
			}
			if ((false == reader.IsDBNull(_.Instructor)))
			{
				this._Instructor = reader.GetString(_.Instructor);
			}
			if ((false == reader.IsDBNull(_.UserID)))
			{
				this._UserID = reader.GetGuid(_.UserID);
			}
			if ((false == reader.IsDBNull(_.AdminID)))
			{
				this._AdminID = reader.GetGuid(_.AdminID);
			}
			if ((false == reader.IsDBNull(_.OccurTime)))
			{
				this._OccurTime = reader.GetDateTime(_.OccurTime);
			}
			if ((false == reader.IsDBNull(_.AuditStatus)))
			{
				this._AuditStatus = reader.GetByte(_.AuditStatus);
			}
			if ((false == reader.IsDBNull(_.Recommend)))
			{
				this._Recommend = reader.GetByte(_.Recommend);
			}
			if ((false == reader.IsDBNull(_.RelationalModel)))
			{
				this._RelationalModel = reader.GetByte(_.RelationalModel);
			}
		}

		public override int GetHashCode()
		{
			return base.GetHashCode();
		}

		public override bool Equals(object obj)
		{
			if ((obj == null))
			{
				return false;
			}
			if ((false == typeof(Article).IsAssignableFrom(obj.GetType())))
			{
				return false;
			}
			if ((((object)(this)) == ((object)(obj))))
			{
				return true;
			}
			return false;
		}

		public class _
		{

			/// <summary>
			/// 表示选择所有列，与*等同
			/// </summary>
			public static AllField All = new AllField<Article>();

			/// <summary>
			/// 字段名：ID - 数据类型：Guid
			/// </summary>
			public static Field ID = new Field<Article>("ID");

			/// <summary>
			/// 字段名：AddTime - 数据类型：DateTime
			/// </summary>
			public static Field AddTime = new Field<Article>("AddTime");

			/// <summary>
			/// 字段名：UpdateTime - 数据类型：DateTime
			/// </summary>
			public static Field UpdateTime = new Field<Article>("UpdateTime");

			/// <summary>
			/// 字段名：IsDeleted - 数据类型：Boolean
			/// </summary>
			public static Field IsDeleted = new Field<Article>("IsDeleted");

			/// <summary>
			/// 字段名：DeleteReason - 数据类型：Byte
			/// </summary>
			public static Field DeleteReason = new Field<Article>("DeleteReason");

			/// <summary>
			/// 字段名：ChannelID - 数据类型：Nullable`1
			/// </summary>
			public static Field ChannelID = new Field<Article>("ChannelID");

			/// <summary>
			/// 字段名：Title - 数据类型：String
			/// </summary>
			public static Field Title = new Field<Article>("Title");

			/// <summary>
			/// 字段名：Summary - 数据类型：String
			/// </summary>
			public static Field Summary = new Field<Article>("Summary");

			/// <summary>
			/// 字段名：Body - 数据类型：String
			/// </summary>
			public static Field Body = new Field<Article>("Body");

			/// <summary>
			/// 字段名：Tags - 数据类型：String
			/// </summary>
			public static Field Tags = new Field<Article>("Tags");

			/// <summary>
			/// 字段名：From - 数据类型：String
			/// </summary>
			public static Field From = new Field<Article>("From");

			/// <summary>
			/// 字段名：Author - 数据类型：String
			/// </summary>
			public static Field Author = new Field<Article>("Author");

			/// <summary>
			/// 字段名：Instructor - 数据类型：String
			/// </summary>
			public static Field Instructor = new Field<Article>("Instructor");

			/// <summary>
			/// 字段名：UserID - 数据类型：Nullable`1
			/// </summary>
			public static Field UserID = new Field<Article>("UserID");

			/// <summary>
			/// 字段名：AdminID - 数据类型：Nullable`1
			/// </summary>
			public static Field AdminID = new Field<Article>("AdminID");

			/// <summary>
			/// 字段名：OccurTime - 数据类型：DateTime
			/// </summary>
			public static Field OccurTime = new Field<Article>("OccurTime");

			/// <summary>
			/// 字段名：AuditStatus - 数据类型：Byte
			/// </summary>
			public static Field AuditStatus = new Field<Article>("AuditStatus");

			/// <summary>
			/// 字段名：Recommend - 数据类型：Byte
			/// </summary>
			public static Field Recommend = new Field<Article>("Recommend");

			/// <summary>
			/// 字段名：RelationalModel - 数据类型：Byte
			/// </summary>
			public static Field RelationalModel = new Field<Article>("RelationalModel");
		}
	}
}
